export const FETCH_CUSTOMER_INFO_SUCCESS = "FETCH_CUSTOMER_INFO_SUCCESS";
export const FETCH_CUSTOMER_INFO_FAILURE = "FETCH_CUSTOMER_INFO_FAILURE";
export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
export const LOGGED_IN_FAILURE = "LOGGED_IN_FAILURE";
export const LOGGED_OUT_SUCCESS = "LOGGED_OUT_SUCCESS";
export const LOGGED_OUT_FAILURE = "LOGGED_OUT_FAILURE";
export const AGENT_AUTHENTICATE = "AGENT_AUTHENTICATE";
export const IS_AGENT_AUTHENTICATED = "IS_AGENT_AUTHENTICATED";
export const SEND_CUSTOMER_INFO = "SEND_CUSTOMER_INFO";
export const SEND_CUSTOMER_DIMPS_ONLINE_STATUS =
  "SEND_CUSTOMER_DIMPS_ONLINE_STATUS";
export const SEND_CUSTOMER_RADIUS_DROPOUT_STATS =
  "SEND_CUSTOMER_RADIUS_DROPOUT_STATS";
